# General settings
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Allow the Node.js container to connect without a password
# (Safe since it's inside the internal Docker network)
listener 1883
allow_anonymous true

# Include the bridging rules IT WILL BE USED WHEN CONFIGURING BRIDGING TO THE CLOUDs
# include_dir /mosquitto/config/conf.d