# WARNING, THIS FILE IS AN EXAMPLE AND MUST BE CUSTOMIZED BEFORE PROD

# Connection name
connection vrfb_to_cloud
address your-cloud-broker.com:1883

# Security (If your cloud broker requires it)
remote_username your_username
remote_password your_password

# Bridging Rules
# "both" = sync data to cloud AND commands from cloud
# "1" = QoS 1 (Essential for queuing data while offline)
# "vrfb/" = The root topic prefix
topic vrfb/# both 1

# Queueing settings
# "cleansession false" ensures the cloud broker remembers
# this Pi and queues messages for it while it's offline.
cleansession false
notifications true
start_type automatic
restart_timeout 30